# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gps_track.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gps_track.proto',
  package='',
  serialized_pb='\n\x0fgps_track.proto\"(\n\x0bMultiTracks\x12\x19\n\x06tracks\x18\x01 \x03(\x0b\x32\t.GpsTrack\"6\n\x08GpsTrack\x12\x0e\n\x06\x63\x61r_id\x18\x01 \x02(\x05\x12\x1a\n\x05point\x18\x02 \x03(\x0b\x32\x0b.TrackPoint\"\xa6\x01\n\nTrackPoint\x12\x0f\n\x07\x65\x61sting\x18\x01 \x02(\x02\x12\x10\n\x08northing\x18\x02 \x02(\x02\x12\x11\n\ttimestamp\x18\x03 \x02(\x05\x12\x0c\n\x04head\x18\x04 \x01(\x05\x12\r\n\x05speed\x18\x05 \x01(\x05\x12\r\n\x05heavy\x18\x06 \x01(\x05\x12\x1b\n\x13horizontal_accuracy\x18\x07 \x01(\x02\x12\x19\n\x11vertical_accuracy\x18\x08 \x01(\x02')




_MULTITRACKS = _descriptor.Descriptor(
  name='MultiTracks',
  full_name='MultiTracks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracks', full_name='MultiTracks.tracks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=59,
)


_GPSTRACK = _descriptor.Descriptor(
  name='GpsTrack',
  full_name='GpsTrack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='car_id', full_name='GpsTrack.car_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point', full_name='GpsTrack.point', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=61,
  serialized_end=115,
)


_TRACKPOINT = _descriptor.Descriptor(
  name='TrackPoint',
  full_name='TrackPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='easting', full_name='TrackPoint.easting', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='northing', full_name='TrackPoint.northing', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='TrackPoint.timestamp', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='head', full_name='TrackPoint.head', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='TrackPoint.speed', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heavy', full_name='TrackPoint.heavy', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='horizontal_accuracy', full_name='TrackPoint.horizontal_accuracy', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vertical_accuracy', full_name='TrackPoint.vertical_accuracy', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=118,
  serialized_end=284,
)

_MULTITRACKS.fields_by_name['tracks'].message_type = _GPSTRACK
_GPSTRACK.fields_by_name['point'].message_type = _TRACKPOINT
DESCRIPTOR.message_types_by_name['MultiTracks'] = _MULTITRACKS
DESCRIPTOR.message_types_by_name['GpsTrack'] = _GPSTRACK
DESCRIPTOR.message_types_by_name['TrackPoint'] = _TRACKPOINT

class MultiTracks(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MULTITRACKS

  # @@protoc_insertion_point(class_scope:MultiTracks)

class GpsTrack(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GPSTRACK

  # @@protoc_insertion_point(class_scope:GpsTrack)

class TrackPoint(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRACKPOINT

  # @@protoc_insertion_point(class_scope:TrackPoint)


# @@protoc_insertion_point(module_scope)
